package com.walmart.interview.wellness.wellnessspringstarter.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.time.ZonedDateTime;

@Data //lombock autogenerated getter and setters
@Builder //lombock object builder
@EqualsAndHashCode
@ToString
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Medication {
    private String name;

    private String dosage;

    private String id;

    private ZonedDateTime createdAt;

    private String prescriptionNumber;
}
