package com.walmart.interview.wellness.wellnessspringstarter.model;

import lombok.Builder;
import lombok.Data;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;

@Data //lombock autogenerated getter and setters
@Builder //lombock object builder
public class Medication {
    private String name;

    private String id;

    private String dosage;

    private ZonedDateTime createdAt;

    private String prescriptionNumber;
}
